admins:
  - ["Nayanne Araújo", "nayanne.bonifacio@planejamento.gov.br"]
  - ["Marisa Souza dos Santos", "marisa.santos@planejamento.gov.br"]
site_url: https://softwarepublico.gov.br
external_hostname: softwarepublico.gov.br
alternative_hostnames:
  - www.softwarepublico.gov.br
  - portal.softwarepublico.gov.br
  - beta.softwarepublico.gov.br
external_ip: 189.9.151.64
alt_ssh_port: 55555
colab_from_address: '"Portal do Software Publico" <noreply@portal.softwarepublico.gov.br>'
server_email: '"Portal do Software Publico" <noreply@portal.softwarepublico.gov.br>'
email_subject_prefix: '[spb]'
lists_hostname: listas.softwarepublico.gov.br
lists_admin: nayanne.bonifacio@planejamento.gov.br
from_address: noreply@softwarepublico.gov.br
relay_hostname: relay.softwarepublico.gov.br
relay_ip: 189.9.151.68
external_outgoing_mail_relay: 189.9.150.53
external_outgoing_mail_domain: serpro.gov.br
raven_dsn: https://4418146896924efe9b73d557f803f047:8a59f39b5f584ff589ecf3dd47faaead@sentry.tracy.com.br/13
google_analytics_id: 'UA-64206731-1'
munin_master: 10.21.0.10
