rpm_repository: https://copr-be.cloud.fedoraproject.org/results/softwarepublico/v4/epel-7-$basearch/
rpm_gpgkey: https://copr-be.cloud.fedoraproject.org/results/softwarepublico/v4/pubkey.gpg
admins:
  - ["Nayanne Araújo", "nayanne.bonifacio@planejamento.gov.br"]
  - ["Marisa Souza dos Santos", "marisa.santos@planejamento.gov.br"]
external_hostname: homologa.softwarepublico.gov.br
sisp_external_hostname: homologa.sisp.gov.br
external_ip: 189.9.151.65
alt_ssh_port: 55555
site_url: https://homologa.softwarepublico.gov.br
colab_from_address: '"Portal do Software Publico (homologação)" <noreply@homologa.softwarepublico.gov.br>'
server_email: '"Portal do Software Publico (homologação)" <noreply@homologa.softwarepublico.gov.br>'
email_subject_prefix: '[spb]'
lists_hostname: listas.homologa.softwarepublico.gov.br
lists_admin: nayanne.bonifacio@planejamento.gov.br
from_address: noreply@homologa.softwarepublico.gov.br
relay_hostname: relay.homologa.softwarepublico.gov.br
relay_ip: 189.9.151.66
external_outgoing_mail_relay: 189.9.150.53
external_outgoing_mail_domain: serpro.gov.br
raven_dsn: https://a5e2f92a83774dfc9de66486e0fe970b:1a9229a4e1d2483582144d302fb53115@sentry.tracy.com.br/19
google_analytics_id: 'UA-64206731-3'
