web_service:
  base_url: http://estruturaorganizacional.dados.gov.br/doc/estrutura-organizacional/resumida.json
  sphere_codes:
    federal: 1
  power_codes:
    executive: 1
    legislative: 2
    judiciary: 3
  additional_params: retornarOrgaoEntidadeVinculados=NAO
  environment_name: Noosfero
  default_community_admin: adminuser