admins:
  - ["Paulo Meirelles", "paulo@softwarelivre.org"]
external_hostname: dev.softwarepublico.gov.br
sisp_external_hostname: dev.sisp.gov.br
external_ip: 189.9.151.16
alternative_hostnames:
  - www.dev.softwarepublico.gov.br
site_url: https://dev.softwarepublico.gov.br
colab_from_address: '"Portal do Software Publico (dev)" <noreply@dev.softwarepublico.gov.br>'
server_email: '"Portal do Software Publico (dev)" <noreply@dev.softwarepublico.gov.br>'
email_subject_prefix: '[spb|dev]'
lists_hostname: listas.dev.softwarepublico.gov.br
lists_admin: paulo@softwarelivre.org
from_address: noreply@dev.softwarepublico.gov.br
relay_hostname: relay.dev.softwarepublico.gov.br
relay_ip: 189.9.151.44
external_outgoing_mail_relay: 189.9.150.53
alt_ssh_port: 55555
external_outgoing_mail_domain: serpro.gov.br
raven_dsn: https://a5e2f92a83774dfc9de66486e0fe970b:1a9229a4e1d2483582144d302fb53115@sentry.tracy.com.br/19
google_analytics_id: 'UA-64206731-2'
dev_backup_frequency: true
disable_send_emails: true
