admins:
  - ["Paulo Meirelles", "paulo@softwarelivre.org"]
external_hostname: dev.softwarepublico.gov.br
external_ip: 189.9.151.16
site_url: https://dev.softwarepublico.gov.br
colab_from_address: '"Portal do Software Publico (dev)" <noreply@dev.softwarepublico.gov.br>'
server_email: '"Portal do Software Publico (dev)" <noreply@dev.softwarepublico.gov.br>'
email_subject_prefix: '[spb|dev]'
lists_hostname: listas.dev.softwarepublico.gov.br
lists_admin: paulo@softwarelivre.org
from_address: noreply@dev.softwarepublico.gov.br
relay_hostname: relay.dev.softwarepublico.gov.br
relay_ip: 189.9.151.44
external_outgoing_mail_relay: 189.9.150.53
alt_ssh_port: 55555
external_outgoing_mail_domain: serpro.gov.br
